spring:
  application:
    name: library-api
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /docs
